### ISSUE TITLE
Unauthorised error when downloading other datasets from LDaCA

### ISSUE THREAD

**Issue by iamyifan** [Australian-Text-Analytics-Platform/cooee#2]
Hi developers, really appreciate your cool work.

Downloading `COOEE` by using your notebook works perfectly to me.

When I'm trying to modify `COLLECTION_ID = 'arcp://name,doi10.4225%2F01%2F4F8E1281B8E2A'` to download another dataset from LDaCA, it returns unauthorised error shown as below:
```bash
ERROR:root:Request failed for access collection arcp://name,doi10.4225%2F01%2F4F8E1281B8E2A with error Unauthorized
ERROR:root:{"error":{"status":"401 Unauthorized","headers":{"WWW-Authenticate":"Bearer error=\"invalid_token\""}}}
```

Does it mean I have no permission to download the dataset? I'm pretty sure my `LDACA_API` and `COLLECTION_ID` are correct.

Thanks a million.

Yifan

**Comment by moisbo** [comment]
Hi Yifan, which one is this collection?

**Comment by iamyifan** [comment]
> Hi Yifan, which one is this collection?

The dataset is [Braided Channels](https://data-uat.ldaca.edu.au/collection?id=arcp%3A%2F%2Fname%2Cdoi10.4225%252F01%252F4F8E1281B8E2A&_crateId=arcp%3A%2F%2Fname%2Cdoi10.4225%252F01%252F4F8E1281B8E2A).

I tried one more time today:
```python
# WARNING: DO NOT CHANGE
LDACA_API = 'https://data.ldaca.edu.au/api'
COLLECTION_ID = 'arcp://name,doi10.4225%2F01%2F4F8E1281B8E2A'

load_dotenv('vars.env')             # Load the environment variables located in the vars.env files
API_TOKEN = os.getenv('API_KEY')    # Store your environment variable in this notebook
if not API_TOKEN:
    print("Get a token from the portal, set a variable in the vars.env file named API_KEY, then restart the kernel.")

# Get the ro-crate metadata. This will create a JSON file under the directory 'metadata'
ldaca = LDaCA(url=LDACA_API, token=API_TOKEN, data_dir='metadata')
ldaca.retrieve_collection(collection=COLLECTION_ID, collection_type='Collection', data_dir='metadata')

# Inspect the metadata
metadata = ldaca.crate
print(metadata)
```

The error says:
```bash
"name": "ValueError",
"message": "There was an error trying to get metadata from API",
"stack": "---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[4], line 3
      1 # Get the ro-crate metadata. This will create a JSON file under the directory 'metadata'
      2 ldaca = LDaCA(url=LDACA_API, token=API_TOKEN, data_dir='metadata')
----> 3 ldaca.retrieve_collection(collection=COLLECTION_ID, collection_type='Collection', data_dir='metadata')
      5 # Inspect the metadata
      6 metadata = ldaca.crate

File ~/anaconda3/envs/southern_cross_ai/lib/python3.12/site-packages/ldaca/ldaca.py:128, in LDaCA.retrieve_collection(self, collection, collection_type, data_dir, clear)
    126 else:
    127     self.membership = response.json()
--> 128     self.retrieve_metadata(self.data_dir)
    129     self.set_crate()
    130     logging.info(f\"Saved crate in {self.crate}\")

File ~/anaconda3/envs/southern_cross_ai/lib/python3.12/site-packages/ldaca/ldaca.py:153, in LDaCA.retrieve_metadata(self, data_dir)
    151 collection = response.json()
    152 if collection.get('error'):
--> 153     raise ValueError(\"There was an error trying to get metadata from API\")
    154 if collection.get('data'):
    155     metadata = collection.get('data')  # this is to stay compatible with older versions of the Oni API

ValueError: There was an error trying to get metadata from API"
```

**Comment by moisbo** [comment]
Gotcha... Have a look at the portal. We are in the process of establishing the ID's not sure what ID was before, however it has changed. Please have a look at the new one in the portal. Also note you are linking data-uat.ldaca.edu.au which is a test environment. The portal is on data.ldaca.edu.au 

cc: @mraadgev

**Comment by iamyifan** [comment]
> Gotcha... Have a look at the portal. We are in the process of establishing the ID's not sure what ID was before, however it has changed. Please have a look at the new one in the portal. Also note you are linking data-uat.ldaca.edu.au which is a test environment. The portal is on data.ldaca.edu.au
> 
> cc: @mraadgev

I will try again this week. Cheers!

**Comment by mraadgev** [comment]
[Braided channels](https://data.ldaca.edu.au/collection?id=arcp%3A%2F%2Fname%2Chdl10.4225~01~4F8E1281B8E2A&_crateId=arcp%3A%2F%2Fname%2Chdl10.4225~01~4F8E1281B8E2A) has an updated @id, it's now `hdl10.4225~01~4F8E1281B8E2A`

**Comment by iamyifan** [comment]
Hi @mraadgev and @moisbo, my code now is running perfectly. 
Thanks for your help : )
